# Utilise le Leurre (decoy) pour distraire les gardes en appuyant sur la dalle marquée d'un X.
hero.moveRight()
hero.moveDown()
hero.moveDown()
hero.moveUp()
hero.moveUp()
hero.moveRight()
hero.moveRight()
hero.moveRight()
hero.moveRight()
